### ISSUE TITLE
Updates to standard pages

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website-jekyll#29]
- Remove website_title
- Publisher: don't link to TDWG, have it as bare text
- Link category to `/standards/status-and-categories/#category`
- Link status to `/standards/status-and-categories/#status`
- Remove double spaces (except in frontmatter)
- Wrap URLs in `<>`
- Have citation appear as normal text, not block quote
- Delete `Documents:`
- Repeat title of part as an h3 header
- Organize part information as a definition list (remove bold, remove `<br>`)

See https://github.com/tdwg/website/commit/c1db999abf6569bfc3efbf71fa787b4a85ac6e86 for an example

---

## Standards updated:

- [x] abcd
- [x] ac
- [x] bph
- [x] bph-supplementum
- [x] delta
- [x] dwc
- [x] economic-botany
- [x] floristic-regions
- [x] ggbn
- [x] guid-as
- [x] hispid3
- [x] ih
- [x] index.md
- [x] itf2
- [x] ncd
- [x] plant-names
- [x] plant-names-authors
- [x] poss
- [x] sdd
- [x] sds
- [x] status-and-categories
- [x] tapir
- [x] tcs
- [x] tl-2
- [x] vms
- [x] wgsrpd
- [x] xdf

---

# Todo

## abcd
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## ac
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [ ] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## bph
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## bph-supplementum
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [ ] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## delta
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## dwc
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [ ] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## economic-botany
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## floristic-regions
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## ggbn
- [x] Remove website_title
- [ ] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [ ] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [ ] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## guid-as
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## hispid3
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## ih
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [ ] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## index.md
- [ ] Remove website_title
- [ ] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [ ] Link status to `/standards/status-and-categories/#status`
- [ ] Remove double spaces (except in frontmatter)
- [ ] Wrap URLs in `<>`
- [ ] Have citation appear as normal text, not block quote
- [ ] Delete `Documents:`
- [ ] Repeat title of part as an h3 header
- [ ] Organize part information as a definition list (remove bold, remove `<br>`)
## itf2
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## ncd
- [ ] Remove website_title
- [ ] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [ ] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [ ] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [ ] Organize part information as a definition list (remove bold, remove `<br>`)
## plant-names
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## plant-names-authors
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [ ] Organize part information as a definition list (remove bold, remove `<br>`)
## poss
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [ ] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## sdd
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## sds
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## status-and-categories
- [ ] Remove website_title
- [ ] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [ ] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [ ] Wrap URLs in `<>`
- [ ] Have citation appear as normal text, not block quote
- [ ] Delete `Documents:`
- [ ] Repeat title of part as an h3 header
- [ ] Organize part information as a definition list (remove bold, remove `<br>`)
## tapir
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## tcs
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## tl-2
- [x] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## vms
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [x] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## wgsrpd
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)
## xdf
- [ ] Remove website_title
- [x] Publisher: don't link to TDWG, have it as bare text
- [ ] Link category to `/standards/status-and-categories/#category`
- [x] Link status to `/standards/status-and-categories/#status`
- [x] Remove double spaces (except in frontmatter)
- [x] Wrap URLs in `<>`
- [x] Have citation appear as normal text, not block quote
- [x] Delete `Documents:`
- [x] Repeat title of part as an h3 header
- [x] Organize part information as a definition list (remove bold, remove `<br>`)

**Comment by peterdesmet** [comment]
This has been discussed with @baskaufs.

**Comment by peterdesmet** [comment]
This has been implemented in https://github.com/tdwg/website/pull/476
